[package]
name = "aoc_12_1_a"
version = "0.1.0"
authors = ["Kellan Elliott-McCrea <kelliott@dropbox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
